-- Only Ghewar has a confirmed price (Rs 400/kg). All other prices are NULL until the owner provides them.
INSERT INTO products (name, price, category, featured) VALUES
    ('Ghewar',                400,  'Ghewar',       TRUE),
    ('Mewa Laddu',            NULL, 'Ladoo',        TRUE),
    ('Barfi',                 NULL, 'Barfi',        TRUE),
    ('Nariyali Barfi',        NULL, 'Barfi',        TRUE),
    ('Milk Cake',             NULL, 'Milk Sweets',  TRUE),
    ('Doda Barfi',            NULL, 'Barfi',        TRUE),
    ('Malai Barfi',           NULL, 'Barfi',        FALSE),
    ('Peda',                  NULL, 'Milk Sweets',  FALSE),
    ('Gond Barfi',            NULL, 'Barfi',        FALSE),
    ('Balushahi',             NULL, 'Syrup Sweets', FALSE),
    ('Malva Ladoo',           NULL, 'Ladoo',        FALSE),
    ('Cham Cham',             NULL, 'Syrup Sweets', FALSE),
    ('Kesari Cham Cham',      NULL, 'Syrup Sweets', FALSE),
    ('White Rasgulla',        NULL, 'Syrup Sweets', FALSE),
    ('Chota Rasgulla',        NULL, 'Syrup Sweets', FALSE),
    ('Gulabi Rasgulla',       NULL, 'Syrup Sweets', FALSE),
    ('Gulab Jamun',           NULL, 'Syrup Sweets', FALSE),
    ('Kala Zam',              NULL, 'Syrup Sweets', FALSE),
    ('Katlas',                NULL, 'Other',        FALSE),
    ('Boondi Ladoo',          NULL, 'Ladoo',        FALSE),
    ('Simple Besan Ladoo',    NULL, 'Ladoo',        FALSE),
    ('Desi Ghee Besan Ladoo', NULL, 'Ladoo',        FALSE),
    ('Kaju Katli',            NULL, 'Barfi',        FALSE);